version: "3.7"

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - frontend

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    networks:
      - frontend
      - backend

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_DB: "validatordb"
    ports:
      - "5432:5432"
    volumes:
      - validator-db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  validator-db:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
